# Generated by Django 5.2.11 on 2026-02-05 05:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("content_ideas", "Content Ideas Generation"),
                            ("tiktok_script", "TikTok Script"),
                            ("instagram_caption", "Instagram Caption"),
                            ("linkedin_post", "LinkedIn Post"),
                            ("twitter_thread", "Twitter Thread"),
                            ("youtube_description", "YouTube Description"),
                            ("voice_analysis", "Voice Profile Analysis"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="System message that sets the AI's role and behavior"
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Template for user message with placeholders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("usage_count", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["prompt_type", "-version"],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("educational", "Educational"),
                            ("entertaining", "Entertaining"),
                            ("promotional", "Promotional"),
                            ("inspirational", "Inspirational"),
                            ("tutorial", "Tutorial"),
                            ("story", "Story/Narrative"),
                            ("news", "News/Update"),
                            ("question", "Question/Poll"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter/X"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        help_text="Template with placeholders like {topic}, {tone}, etc."
                    ),
                ),
                (
                    "example_output",
                    models.TextField(
                        blank=True, help_text="Example of what this template produces"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["platform", "template_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        help_text="The topic or subject for content generation"
                    ),
                ),
                (
                    "additional_context",
                    models.TextField(
                        blank=True, help_text="Additional context or requirements"
                    ),
                ),
                ("target_platforms", models.JSONField(default=list)),
                ("creativity_level", models.IntegerField(default=7)),
                ("include_hashtags", models.BooleanField(default=True)),
                ("include_emojis", models.BooleanField(default=True)),
                (
                    "content_length",
                    models.CharField(
                        choices=[
                            ("short", "Short"),
                            ("medium", "Medium"),
                            ("long", "Long"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("content_ideas", models.JSONField(default=list)),
                ("selected_idea", models.TextField(blank=True)),
                ("tiktok_script", models.TextField(blank=True)),
                ("instagram_caption", models.TextField(blank=True)),
                ("linkedin_post", models.TextField(blank=True)),
                ("twitter_thread", models.JSONField(default=list)),
                ("youtube_description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("generation_time_seconds", models.FloatField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.voiceprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ]
                    ),
                ),
                (
                    "creativity_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "relevance_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "voice_match_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("improvement_suggestions", models.TextField(blank=True)),
                ("platforms_used", models.JSONField(default=list)),
                ("content_modified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_generation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="content_generation.contentgeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("saved_platforms", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="content_generation.contentgeneration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "content_generation")},
            },
        ),
    ]
