# Generated by Django 5.2.11 on 2026-02-05 05:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content_generation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("content_type", models.JSONField(default=list)),
                ("content_tone", models.JSONField(default=list)),
                ("target_platforms", models.JSONField(default=list)),
                ("preferred_video_styles", models.JSONField(default=list)),
                ("preferred_moods", models.JSONField(default=list)),
                ("preferred_pace", models.JSONField(default=list)),
                ("weight_tone", models.FloatField(default=0.3)),
                ("weight_pace", models.FloatField(default=0.2)),
                ("weight_style", models.FloatField(default=0.3)),
                ("weight_platform", models.FloatField(default=0.2)),
                ("is_active", models.BooleanField(default=True)),
                ("min_match_score", models.FloatField(default=0.5)),
                ("times_applied", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VideoAnalysisPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("visual_mood", "Visual Mood Analysis"),
                            ("audio_tone", "Audio Tone Analysis"),
                            ("pace_detection", "Pace Detection"),
                            ("style_classification", "Style Classification"),
                            ("scene_breakdown", "Scene Breakdown"),
                            ("content_matching", "Content Matching"),
                        ],
                        max_length=30,
                    ),
                ),
                ("system_prompt", models.TextField()),
                ("user_prompt_template", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("usage_count", models.IntegerField(default=0)),
                ("average_accuracy", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["analysis_type", "-version"],
            },
        ),
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="videos/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="video_thumbnails/"
                    ),
                ),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("resolution_width", models.IntegerField(blank=True, null=True)),
                ("resolution_height", models.IntegerField(blank=True, null=True)),
                ("fps", models.FloatField(blank=True, null=True)),
                ("file_size_mb", models.FloatField(blank=True, null=True)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("energetic", "Energetic"),
                            ("calm", "Calm"),
                            ("serious", "Serious"),
                            ("playful", "Playful"),
                            ("inspirational", "Inspirational"),
                            ("dramatic", "Dramatic"),
                            ("minimal", "Minimal"),
                            ("vibrant", "Vibrant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pace",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slow", "Slow (0-30 cuts/min)"),
                            ("medium", "Medium (30-60 cuts/min)"),
                            ("fast", "Fast (60+ cuts/min)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lifestyle", "Lifestyle"),
                            ("tutorial", "Tutorial/Educational"),
                            ("product_demo", "Product Demo"),
                            ("talking_head", "Talking Head"),
                            ("b_roll", "B-Roll/Cinematic"),
                            ("animation", "Animation/Motion Graphics"),
                            ("screen_record", "Screen Recording"),
                            ("testimonial", "Testimonial"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "visual_analysis",
                    models.JSONField(
                        default=dict, help_text="AI analysis of visual elements"
                    ),
                ),
                (
                    "audio_analysis",
                    models.JSONField(
                        default=dict, help_text="AI analysis of audio elements"
                    ),
                ),
                (
                    "scene_analysis",
                    models.JSONField(
                        default=dict, help_text="Scene-by-scene breakdown"
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                ("suitable_platforms", models.JSONField(default=list)),
                ("times_matched", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoProcessingQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("thumbnail_generation", "Thumbnail Generation"),
                            ("video_analysis", "Video Analysis"),
                            ("audio_extraction", "Audio Extraction"),
                            ("scene_detection", "Scene Detection"),
                            ("content_matching", "Content Matching"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                ("result_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("priority", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_tasks",
                        to="video_matching.videoasset",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentVideoMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_score", models.FloatField()),
                (
                    "match_quality",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent (90-100%)"),
                            ("good", "Good (70-89%)"),
                            ("fair", "Fair (50-69%)"),
                            ("poor", "Poor (0-49%)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "match_reasoning",
                    models.TextField(
                        help_text="AI explanation of why this is a good match"
                    ),
                ),
                ("tone_match_score", models.FloatField(default=0.0)),
                ("pace_match_score", models.FloatField(default=0.0)),
                ("style_match_score", models.FloatField(default=0.0)),
                ("platform_match_score", models.FloatField(default=0.0)),
                ("recommended_platforms", models.JSONField(default=list)),
                ("timing_suggestions", models.JSONField(default=dict)),
                ("editing_suggestions", models.JSONField(default=list)),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_platforms", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_matches",
                        to="content_generation.contentgeneration",
                    ),
                ),
                (
                    "video_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_matches",
                        to="video_matching.videoasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score"],
                "unique_together": {("content_generation", "video_asset")},
            },
        ),
    ]
